### ISSUE TITLE
mobile-menu drawer functionality

### ISSUE THREAD

**Issue by flicksolutions** [DHBern/becher-frontend#2]
optimize the functionality of the mobile Menu.

- The height should adapt to the height of the menu. (Do not use magic numbers - it should adapt to any size of the menu)
- fix the z-index of the text on the home-page: 
![z-index too big](https://github.com/DHBern/becher-frontend/assets/33655122/dd5d6476-106b-4ebf-a17c-a5d0cc33c6af)
 This is an bug I introduced. The Text should not be highlightable. a click onto the rest of the page should close the drawer.

changes are likely to be in `src\routes\+layout.svelte` and `src\routes\+page.svelte`.

**Comment by ZEDz318** [comment]
I fixed the height to have it dynamic
Also, i used event pointer non instead of changing z-index to prevent the background from being selectable. It appears to serve the same purpose. Tell me if this is not how you want it.
