### ISSUE TITLE
Change related items from truncated ID to category adherence

### ISSUE THREAD

**Issue by pdaengeli** [DHBern/becher-frontend#6]
`i.key.startsWith(params.slug.slice(0, -2))` --> `i.category === item.category`

As done in https://github.com/DHBern/becher-frontend/commit/6ea498338a9a6cfb6335073a372eb85228f094f0 and subsequently reverted for workflow reasons.

**Comment by flicksolutions** [comment]
Done in [c2adb7c](https://github.com/DHBern/becher-frontend/commit/c2adb7c4469c350fa3aafcc026698abada475ad2).
ok like that @pdaengeli ?

**Comment by pdaengeli** [comment]
Looks good, thanks.
