### ISSUE TITLE
Normalized dates (search and item view)

### ISSUE THREAD

**Issue by pdaengeli** [DHBern/becher-frontend#7]
## Data update

* <del>[data-output-full-20240524.zip](https://github.com/DHBern/becher-frontend/files/15431649/data-output-full-20240524.zip)</del>
* [data-output-20240524-a.zip](https://github.com/DHBern/becher-frontend/files/15432093/data-output-20240524-a.zip) (`vikus.csv` fixed)

New addition: `date_reg`:

```diff
   "date": [ "16. Juli bis 19. September 1961" ],
+  "date_reg": [ "1961-07-16" ],
```

## Necessary frontend adjustments

- [x] use `date_reg` for search/filter
- [x] do not show `date_reg` on item view

**Comment by pdaengeli** [comment]
NB: the structure of `vikus.csv` is bad; an update will follow in #8 

Edit: done

**Comment by flicksolutions** [comment]
@pdaengeli, please clarify:
- Fulltext search should still search over **all** fields. _date_ and _date_reg_. correct?
- should the field "Entstehungszeitraum" now be _date_reg_ instead of _date_? If so, please update structure.json
   - it would not be possible to search specificly in _date_?

**Comment by flicksolutions** [comment]
20aa445a9650fb8fd5ac90c2cb79e17f08d06190 optimized fuzzyness and also allows `-` to be part of a term (tokenization).
Should be done for now. implementation of fuzzy-switch is possible in the future. What do you think @pdaengeli ?

**Comment by pdaengeli** [comment]
As discussed, here is a new `structure.json` containing the `search` object as well as some `info` strings for rendering as field tooltips:

[structure.json](https://github.com/user-attachments/files/15759181/structure.json)

```json
[
  {
    "type": "search",
    "fields": [
      { "label":"Titel", "key":"title" },
      {
        "label": "Verfasser \/ Absender",
        "key": "creator",
        "info": "Die aktuelle Umsetzung berücksichtigt die Feldinhalte der Datenbank(en). Vorgesehen ist eine Normdaten-basierte Suche, die z.B. Namensvarianten mitberücksichtigt."
      },
     etc
```
 
```
Verfasser / Absender ⓘ
+----------------------------------+
|                                  |
+----------------------------------+


Tooltip:
         +---------------------------+
         | Die aktuelle Umsetzung    |
         | berücksichtigt die        |
         | Feldinhalte der           |
         | Datenbank(en).  …         |
         +---------------------------+
                     \/
Verfasser / Absender ⓘ
+----------------------------------+
|                                  |
+----------------------------------+
``

**Comment by flicksolutions** [comment]
Sorry, @pdaengeli I didn't mean to close the issue; I just wanted to mention it.
What do you think about my solution to the popups?
It's absolutely also possible to do it like you wanted it witrh the icons - but I thought this makes it a bit more prominent. feel free to reopen the issue

**Comment by pdaengeli** [comment]
Very apt solution for a prototype, thanks.
