### ISSUE TITLE
Normalized dates (vikus)

### ISSUE THREAD

**Issue by pdaengeli** [DHBern/becher-frontend#8]
## Data update

* [vikus.csv](https://github.com/DHBern/becher-frontend/files/15432059/vikus.csv)
* change: fewer missing `year` values

## Necessary frontend adjustments

- [x] use new `vikus.csv` for build

**Comment by flicksolutions** [comment]
done with https://github.com/DHBern/vikus-viewer/commit/0ef82bffa29b7728f206778010264deb35036d09

Please create issues for vikus viewer there (in the future).
